---
title: "avastin_lucentis_arms_eda"
author: "Darren S Thomas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
always_allow_html: yes
output: github_document
---
# setup

```{r setup, include=FALSE}
# configure Rmd chunks
knitr::opts_chunk$set(
    echo = TRUE,      # output code chunks
    message = FALSE,  # toggle off message output 
    warning = FALSE)  # toggle off warning output

# load frequently used packages
library(tidymodels)
library(tidyverse)
library(patchwork)

# set default ggplot theme
courier_bw <- theme_bw() +
  theme(text = element_text(family = "Courier"),
        legend.position = "bottom")

theme_set(courier_bw)

# configure connection to mysql
source("src/kale_mysql.R")

# source code to pre-process, run, and post-process glm (for em + psm)
source("fnc/va_glm.R")

# source code to pre-process, run, and post-process weighted glm (for ipwt)
source("fnc/va_weighted_glm.R")
```

# read_from_csv

```{r}
abc <- read_csv("data/abc_patient_details.csv",
                col_types = cols(
                  id = col_character(),
                  age_at_baseline = col_integer(),
                  baseline_etdrs = col_integer(),
                  injection_count = col_integer(),
                  drug_recency = col_integer(),
                  study_exit_va = col_integer()
                )) %>% 
  rename(
    age = age_at_baseline,
    drug_load = injection_count) %>% 
  # reorder
  select(
    id,
    treatment, 
    age, 
    gender,
    baseline_etdrs,
    drug_load,
    drug_recency,
    study_exit_va) %>% 
  # restrict to avastin arm
  filter(treatment == "avastin")
```


# import_from_mysql

```{sql connection = kale, output.var = "avastin"}
-- only select eligibility criteria
SELECT patient_eye AS id,
treatment,
age_at_baseline AS age,
gender,
baseline_va AS baseline_etdrs,
drug_load,
drug_recency,
study_exit_va,
baseline_avastin_date AS year_initiation
FROM amd_synthetic_avastin_arm_study_table
WHERE index_eye = 1 AND
      incomplete_loading_excl = 0 AND
      missing_covariates_excl = 0 AND
      incomplete_followup_excl = 0 AND
      previous_vegf_excl = 0 AND 
      switch_excl = 0;
```

```{sql connection = kale, output.var = "lucentis"}
-- only select eligibility criteria
SELECT patient_eye AS id,
treatment,
age_at_baseline AS age,
gender,
baseline_va AS baseline_etdrs,
drug_load,
drug_recency,
study_exit_va,
baseline_lucentis_date AS year_initiation
FROM amd_synthetic_lucentis_arm_study_table
WHERE index_eye = 1 AND
      incomplete_loading_excl = 0 AND
      missing_covariates_excl = 0 AND
      incomplete_followup_excl = 0 AND
      previous_vegf_excl = 0 AND 
      switch_excl = 0;
```

# drug_load

```{r}
a <- avastin %>% 
  group_by(treatment, drug_load) %>% 
  count() %>% 
  ggplot(aes(x = factor(drug_load), y = n)) +
  geom_bar(stat = "identity") +
  labs(
    title = "Avastin",
    x = "Maintanence injections")

b <- lucentis %>% 
  group_by(treatment, drug_load) %>% 
  count() %>% 
  ggplot(aes(x = factor(drug_load), y = n)) +
  geom_bar(stat = "identity") +
  labs(
    title = "Lucentis",
    x = "Maintanence injections")

a + b
```

# initiation_by_year

```{r}
c <- avastin %>% 
  mutate(year_initiation = lubridate::year(lubridate::ymd(year_initiation))) %>% 
  group_by(year_initiation) %>% 
  count() %>% 
   ggplot(aes(x = factor(year_initiation), y = n)) +
  geom_bar(stat = "identity") +
  labs(
    title = "Avastin",
    x = "Year of baseline") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

d <- lucentis %>% 
  mutate(year_initiation = lubridate::year(lubridate::ymd(year_initiation))) %>% 
  group_by(year_initiation) %>% 
  count() %>% 
   ggplot(aes(x = factor(year_initiation), y = n)) +
  geom_bar(stat = "identity") +
  labs(
    title = "Lucentis",
    x = "Year of baseline") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

c + d
```


# exact_matching
How many exact matches?

```{sql connection = kale, output.var = "avastin"}
SELECT patient_eye AS id,
treatment,
age_at_baseline AS age,
gender,
baseline_va AS baseline_etdrs,
drug_load,
drug_recency,
study_exit_va
FROM amd_synthetic_avastin_arm_study_table
WHERE eligibility = 1;
```


```{sql connection = kale, output.var = "eylea"}
-- only select eligibility criteria
SELECT patient_eye AS id,
treatment,
age_at_baseline AS age,
gender,
baseline_va AS baseline_etdrs,
drug_load,
drug_recency,
study_exit_va
FROM amd_synthetic_eylea_arm_study_table
WHERE eligibility = 1;
```

```{r}
# source exact_matching code
source("fnc/exact_matching.R")
```

```{r}
# run exact_matching_algortihm
em <- exact_matching(abc, avastin)
```
