---
title: "eylea_frequency"
author: "Darren S Thomas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
always_allow_html: yes
output: github_document
---
# setup

```{r setup, include=FALSE}
# configure Rmd chunks
knitr::opts_chunk$set(
    echo = TRUE,      # output code chunks
    message = FALSE,  # toggle off message output 
    warning = FALSE)  # toggle off warning output

# load frequently used packages
library(tidymodels)
library(tidyverse)
library(patchwork)

# set default ggplot theme
courier_bw <- theme_bw() +
  theme(text = element_text(family = "Courier"),
        legend.position = "bottom")

theme_set(courier_bw)

# configure connection to mysql
source("src/kale_mysql.R")
```

# Is Eylea admninistered q8w?

```{sql connection = kale, output.var = "eylea.injections"}
SELECT i.patient_eye, 
       i.EncounterDate AS encounter_date,
       i.InjectedDrugDesc AS injected_drug_desc,
       cumulative_injection_count,
       days_since_last_injection
FROM nvAMD_injections i
INNER JOIN amd_synthetic_eylea_arm_study_table s
ON i.patient_eye = s.patient_eye
WHERE s.eligibility = 1 AND
      i.EncounterDate > s.third_injection_date AND -- maintenance injections only
      i.EncounterDate < s.study_exit
; 
```

```{r}
eylea.injections <- eylea.injections %>% 
  as_tibble() %>% 
  arrange(
    patient_eye,
    encounter_date
  ) %>% 
  mutate(encounter_date = lubridate::ymd(encounter_date))
```

```{r}
# injection intervals vs year
eylea.injections %>% 
  mutate(encounter_year = lubridate::year(encounter_date)) %>% 
  group_by(encounter_year) %>% 
  summarise(
    mean_intervals = round(mean(days_since_last_injection), 0),
    median_intervals = round(median(days_since_last_injection), 0)
  ) %>% 
  ggplot(aes(x = as.factor(encounter_year), y = mean_intervals)) +
  geom_bar(stat = "identity") +
  geom_hline(yintercept = 8 * 7) +
  scale_y_continuous(breaks = seq(0, 70, 10)) +
  labs(
    title = "Frequency of Aflibercept injections alligns with guidelines",
    x = "Calendar year of administration",
    y = "Mean days since previous injection")
```

