---
title: "exchangeability"
author: "Darren S Thomas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
always_allow_html: yes
output: github_document
---

```{r setup, include=FALSE}
# configure Rmd chunks
knitr::opts_chunk$set(
    echo = TRUE,      # output code chunks
    message = FALSE,  # toggle off message output 
    warning = FALSE)  # toggle off warning output

# load frequently used packages
library(broom)
library(tidyverse)

# set default ggplot theme
courier_bw <- theme_bw() +
  theme(text = element_text(family = "Courier"),
        legend.position = "bottom",
        strip.background = element_rect(
          colour = "black", 
          fill = "white",
          size = 0.5))

theme_set(courier_bw)
```

# read_data

```{r}
# create list of filenames to read from
y <- list(
  "data/cohort_nc.csv",
  "data/cohort_iptw.csv",
  "data/cohort_em.csv",
  "data/cohort_psm.csv"
)

# read cohorts from .csv
z <- map(
  .x = y,
  ~ read_csv(
    file = .x,
    col_types = cols(
      treatment = col_factor(levels = c('eylea', 'avastin'))
    ))
)

# name each element of list
names(z) <- c('nc', 'iptw', 'em', 'psm')

# add var to identify each cohort when lists are merged
z <- map2(
  .x = z,
  .y = list('nc', 'iptw', 'em', 'psm'),
  ~ mutate(
    .x,
    cohort = .y
  )
)

# add weight var (ipw weights will be updated later)
z <- map(
  .x = z,
  ~ mutate(
    .x,
    weight = 1)
)

# select only cont. confounders
z <- map(
  .x = z,
  ~ select(.x, id, age, baseline_etdrs, cohort, treatment, weight)
)

# combine individual elements into a singl df
zz <- do.call(rbind.data.frame, z)
```

```{r}
# pivot longer
zz <- zz %>% 
  pivot_longer(
    cols = age:baseline_etdrs,
    names_to = "var",
    values_to = "unit"
  )
```

```{r}
# dev_testing of weights for iptw
w <- read_csv("data/cohort_iptw.csv") %>% 
  select(id, treatment, age, baseline_etdrs, ipw) %>% 
  pivot_longer(
    cols = age:baseline_etdrs,
    names_to = "var",
    values_to = "unit"
  )
+ facet_grid(. ~ fl)
w %>% 
  ggplot(aes(x = unit, colour = treatment, weight = ipw)) +
    facet_grid(
    . ~ var,
    scales = "free_x") +
  geom_density(alpha = 0.5) +
  scale_colour_discrete(
    name = NULL,
    labels = c("Aflibercept", "Eylea")) +
  labs(
    x = NULL,
    y = "Density")
```


```{r}
# assign facet labels to vectors
cohort_lbl <- c(
  "nc" = "NC", 
  "iptw" = "IPTW", 
  "em" = "EM", 
  "psm" = "PSM")

var_lbl <- c(
  "age" = "Age at baseline (years)", 
  "baseline_etdrs" = "Baseline read (ETDRS)")

# plot
zz %>% 
  mutate(cohort = factor(cohort, levels = c("nc", "iptw", "em", "psm"))) %>% 
  ggplot(aes(x = unit, colour = treatment)) +
  facet_grid(
    cohort ~ var,
    scales = "free_x",
    labeller = labeller(
      var = var_lbl,
      cohort = cohort_lbl
    )) +
  geom_density(alpha = 0.5) +
  scale_colour_discrete(
    name = NULL,
    labels = c("Aflibercept", "Eylea")) +
  labs(
    x = NULL,
    y = "Density")
```

To do: 

* iptw is not weighted!
* annotate with AUC

#### dev

  facet_grid(
    cohort ~ var,
    switch = "y",
    scales = "free_x")