---
title: "outcome_regression"
author: "Darren S Thomas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
always_allow_html: yes
output: github_document
---

```{r setup, include=FALSE}
# configure Rmd chunks
knitr::opts_chunk$set(
    echo = TRUE,      # output code chunks
    message = FALSE,  # toggle off message output 
    warning = FALSE)  # toggle off warning output

# load frequently used packages
library(tidymodels)
library(tidyverse)

# set default ggplot theme
courier_bw <- theme_bw() +
  theme(text = element_text(family = "Courier"),
        legend.position = "bottom")

theme_set(courier_bw)
```

# read_data

```{r}
# create list of filenames to read from
y <- list(
  "data/cohort_nc.csv",
  "data/cohort_iptw.csv",
  "data/cohort_em.csv",
  "data/cohort_psm.csv"
)

# read cohorts from .csv
z <- map(
  .x = y,
  ~ read_csv(
    file = .x,
    col_types = cols(
      treatment = col_factor(levels = c('eylea', 'avastin'))
    ))
)

# name each element of list
names(z) <- c('nc', 'iptw', 'em', 'psm')

# extract each elelment of list as tbl
nc <- z %>% pluck("nc")

iptw <- z %>% pluck("iptw")
  
em <- z %>% pluck("em")

psm <- z %>% pluck("psm")
```

# source_fncs

```{r}
# source code to pre-process, run, and post-process glm (for em + psm)
source("fnc/va_glm.R")

# source code to pre-process, run, and post-process weighted glm (for ipwt)
source("fnc/va_weighted_glm.R")
```

# nc

```{r}
nc <- nc %>% 
  va_glm()
```

```{r}
# ≥ 15 letters
nc[[6]][[1]]
```

```{r}
# ≥ 10 letetrs 
nc[[6]][[2]]
```

```{r}
# > -15 letters
negative.control[[6]][[3]]
```

# iptw

```{r}
iptw <- iptw %>% 
  va_glm(weights = iptw$ipw)
```

```{r}
# ≥ 15 letters
iptw[[6]][[1]]
```

```{r}
# ≥ 10 letetrs 
iptw[[6]][[2]]
```

```{r}
# > -15 letters
iptw[[6]][[3]]
```

# em

```{r}
em <- em %>% 
  va_glm()
```

```{r}
# ≥ 15 letters
em[[6]][[1]]
```

```{r}
# ≥ 10 letetrs 
em[[6]][[2]]
```

```{r}
# > -15 letters
em[[6]][[3]]
```

# psm

```{r}
psm <- psm %>% 
  va_glm()
```

```{r}
# ≥ 15 letters
psm[[6]][[1]]
```

```{r}
# ≥ 10 letters 
psm[[6]][[2]]
```

```{r}
# > -15 letters
psm[[6]][[3]]
```