---
title: "eylea_em"
author: "Darren S Thomas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
always_allow_html: yes
output: github_document
---
# setup

```{r setup, include=FALSE}
# configure Rmd chunks
knitr::opts_chunk$set(
    echo = TRUE,      # output code chunks
    message = FALSE,  # toggle off message output 
    warning = FALSE)  # toggle off warning output

# load frequently used packages
library(tidymodels)
library(tidyverse)

# set default ggplot theme
courier_bw <- theme_bw() +
  theme(text = element_text(family = "Courier"),
        legend.position = "bottom")

theme_set(courier_bw)

# configure connection to mysql
source("src/kale_mysql.R")

# source code to pre-process, run, and post-process glm (for em + psm)
source("fnc/va_glm.R")

# source code to pre-process, run, and post-process weighted glm (for ipwt)
source("fnc/va_weighted_glm.R")
```

# read_from_csv

```{r}
abc <- read_csv("data/abc_patient_details.csv",
                col_types = cols(
                  id = col_character(),
                  age_at_baseline = col_integer(),
                  baseline_etdrs = col_integer(),
                  injection_count = col_integer(),
                  drug_recency = col_integer(),
                  study_exit_va = col_integer()
                )) %>% 
  rename(
    age = age_at_baseline,
    drug_load = injection_count) %>% 
  # reorder
  select(
    id,
    treatment, 
    age, 
    gender,
    baseline_etdrs,
    drug_load,
    drug_recency,
    study_exit_va) %>% 
  # restrict to avastin arm
  filter(treatment == "avastin")
```

# import_from_mysql

```{sql connection = kale, output.var = "ehr"}
SELECT patient_eye AS id,
treatment,
age_at_baseline AS age,
gender,
baseline_va AS baseline_etdrs,
drug_load,
drug_recency,
study_exit_va
FROM amd_synthetic_eylea_arm_study_table
WHERE eligibility = 1;
```

```{r}
ehr <- as.tibble(ehr)
```

# no_matching

```{r}
# combine avastin (n 65) and eylea (n 4,471) arms
negative.control <- bind_rows(abc, ehr)
```

## intention_to_treat

```{r}
negative.control <- negative.control %>% 
  va_glm()
```

## per protocol

# exact_matching

```{r}
# source exact_matching code
source("fnc/exact_matching.R")
```

```{r}
# run exact_matching_algortihm
em <- exact_matching(abc, ehr)
```

## intention_to_treat

```{r}
em <- em %>% 
  va_glm()
```

## per protocol

# psm

```{r}
# source psm code
source("fnc/propensity_score_matching.R")
```

## single_iteration

```{r}
zedd <- propensity_score_matching(
  trial_arm  = abc,
  synthetic_arm = ehr,
  iterations = 1,
  caliper_sd = 0.1
)
```

```{r}
# cheat solution while propensity_score_matching fnc optimised
psm <- read_csv("data/psm_first_iteration.csv")
```

```{r}
xyz <- psm %>% 
  va_glm()
```


## multiple_iterations

```{r}
# preprocess data
trial.list.column <- propensity_score_matching(
  trial = abc, 
  iterations = 50)
```

```{r}
## calculate propensity_score width of 0.1 standard deviation
  caliper_ps <- trial.list.column %>% 
    unnest() %>% 
    ungroup() %>% 
    filter(iteration == 1)
  
  caliper_ps <- (sd(caliper_ps$propensity_score) * 0.1)  ###!!! sd / 10 == 0.1 SD?
```

```{r}
# create empty vector to supply to use as a match counter
empty.vector <- vector(mode = "character") ###!!!

# apply fuzzy_left_join_without_replacement() with map()
julio <- trial.list.column %>% 
  mutate(
    match = map( 
    .x = data,
    ~ fuzzy_left_join_without_replacement(
      trial.list.column = .x,
      synthetic = ehr,
      caliper = caliper_ps
    )
  ))
```

```{r}
  # unnest at the end(), ungroub(), group_by(iteration), nest()
```


## per protocol


# iptw

```{r}
# source ipt code
source("fnc/inverse_probability_treatment.R")
```


```{r}
# run ipt algorithm
iptw <- inverse_probability_treatment(abc, ehr)
```

```{r}
# run primary analysis fucntion
iptw <- iptw %>% 
  va_weighted_glm() ###!!!  r unify with va_glm.R
```

## intention_to_treat

## per protocol

