---
title: "outcome_regression"
author: "Darren S Thomas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
always_allow_html: yes
output: github_document
---

```{r setup, include=FALSE}
# configure Rmd chunks
knitr::opts_chunk$set(
    echo = TRUE,      # output code chunks
    message = FALSE,  # toggle off message output 
    warning = FALSE)  # toggle off warning output

# load frequently used packages
library(broom)
library(tidyverse)

# set default ggplot theme
courier_bw <- theme_classic() +
  theme(text = element_text(family = "Courier"),
        legend.position = "bottom",
        axis.text.y = element_text(
          face = "bold", 
          size = 14,
          hjust = 0.5),
        axis.ticks = element_blank(),
        axis.line.y = element_blank())

theme_set(courier_bw)
```

# read_data

```{r}
# create list of filenames to read from
y <- list(
  "../data/cohort_nc.csv",
  "../data/cohort_iptw.csv",
  "../data/cohort_em.csv",
  "../data/cohort_psm.csv"
)

# read cohorts from .csv
z <- map(
  .x = y,
  ~ read_csv(
    file = .x,
    col_types = cols(
      treatment = col_factor(levels = c('eylea', 'avastin'))
    ))
)

# name each element of list
names(z) <- c('uc', 'iptw', 'em', 'psm')

# extract each elelment of list as tbl
uc <- z %>% pluck("uc")

iptw <- z %>% pluck("iptw")
  
em <- z %>% pluck("em")

psm <- z %>% pluck("psm")
```

# source_fncs

```{r}
# source code to pre-process, run, and post-process glm (for em + psm)
source("../fnc/va_glm.R")
```

# uc

```{r}
uc <- uc %>% 
  # add null weights
  mutate(weights = 1) %>% 
  va_glm()
```

```{r}
# ≥ 15 letters
uc[[6]][[1]]
```

```{r}
# ≥ 10 letetrs 
uc[[6]][[2]]
```

```{r}
# > -15 letters
uc[[6]][[3]]
```

```{r}
# extract .glm output
uc.glm <- uc %>% 
  select(
    outcome,
    tidy_output
  ) %>% 
  unnest(cols = tidy_output) %>% 
  mutate(method = "UC")

uc.glm
```

# iptw

```{r}
iptw <- iptw %>% 
  va_glm(weights = iptw$ipw)
```

```{r}
# ≥ 15 letters
iptw[[6]][[1]]
```

```{r}
# ≥ 10 letetrs 
iptw[[6]][[2]]
```

```{r}
# > -15 letters
iptw[[6]][[3]]
```

```{r}
# extract .glm output
iptw.glm <- iptw %>% 
  select(
    outcome,
    tidy_output
  ) %>% 
  unnest(cols = tidy_output) %>% 
  mutate(method = "IPTW")

iptw.glm
```

# em

```{r}
em <- em %>% 
  # add null weights
  mutate(weights = 1) %>% 
  va_glm()
```

```{r}
# ≥ 15 letters
em[[6]][[1]]
```

```{r}
# ≥ 10 letetrs 
em[[6]][[2]]
```

```{r}
# > -15 letters
em[[6]][[3]]
```

```{r}
# extract .glm output
em.glm <- em %>% 
  select(
    outcome,
    tidy_output
  ) %>% 
  unnest(cols = tidy_output) %>% 
  mutate(method = "EM")

em.glm
```

# psm

```{r}
psm <- psm %>% 
  # add null weights
  mutate(weights = 1) %>% 
  va_glm()
```

```{r}
# ≥ 15 letters
psm[[6]][[1]]
```

```{r}
# ≥ 10 letters 
psm[[6]][[2]]
```

```{r}
# > -15 letters
psm[[6]][[3]]
```

```{r}
# extract .glm output
psm.glm <- psm %>% 
  select(
    outcome,
    tidy_output
  ) %>% 
  unnest(cols = tidy_output)%>% 
  mutate(method = "PSM")

psm.glm
```

# forest_plot

```{r}
# bind .glm outputs
sup <- bind_rows(
  uc.glm,
  iptw.glm,
  em.glm,
  psm.glm
) %>% 
  # rename broom::tidy() outputs
  rename(
    or = estimate,
    lo95 = conf.low,
    hi95 = conf.high
  ) %>% 
  # 
  mutate(outcome = case_when(
    outcome == "fifteen_gain" ~ "≥ 15 letters",
    outcome == "ten_gain" ~ "≥ 10 letters",
    outcome == "fifteen_loss" ~ "> -15 letters"
  ))
```


```{r}
# convert to point estimate and confidence intervals to strings (to keep trailing zeros for plot)

to_string <- function(
  var,
  n_digits = 2,
  n_small = 2){
    
  as.character(format(round(var, digits = n_digits), nsmall = n_small))
  
  }
```

```{r}

sup <- sup %>% 
  mutate(
    or_lab = to_string(or),
    lo95_lab = to_string(lo95),
    hi95_lab = to_string(hi95),
    lab = str_c(
      str_trim(or_lab),
      "(",
      str_trim(lo95_lab),
      "-",
      str_trim(hi95_lab),
      ")"
    )
  )

```


```{r}
# plot, faceted by adjustment
sup %>% 
  filter(term != "(Intercept)") %>% 
  mutate(
    method = factor(method, levels = c("PSM", "EM", "IPTW", "UC")),
    outcome = factor(outcome, levels = c('≥ 15 letters', '≥ 10 letters', '> -15 letters'))) %>% 
ggplot(aes(x = or, y = method)) +
  facet_grid(.~outcome) +
  # log scale
  scale_x_log10(breaks = c(0.25, 0.5, 1, 2, 4)) +
  # add line of no effect
  geom_vline(
    xintercept = 1,
    linetype = "dashed",
    colour = 'grey'
  ) +
  # add confidence intervals
  geom_errorbarh(aes(
    xmin = lo95,
    xmax = hi95,
    height = 0
  )) +
  # add point estimates
  geom_point(
    size = 7,
    shape = 18) +
  # add text for point estimates and confidence intervals
  geom_text(aes(
    family = 'Courier',
    label = lab),
    parse = FALSE,
    nudge_y = -0.2) +
  # ammend visuals
  labs(
    x = "Odds Ratio (95% Confidence Interval)",
    y = NULL) +
  theme(legend.position = "none")
```

```{r}
# export as .tiff
ggsave(
  filename = "fig_3.tiff",
  plot = last_plot(),
  device = "tiff",
  path = "../figs",
  width = 178,
  height = 100,
  units = "mm",
  dpi = 300
)
```

```{r info, echo = FALSE}
print(sessionInfo())
```