---
title: "1_survival_analysis"
author: "Darren S Thomas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
always_allow_html: yes
output: github_document
---

```{r setup, include=FALSE}
# configure Rmd chunks
knitr::opts_chunk$set(
    echo = TRUE,      # output code chunks
    message = FALSE,  # toggle off message output 
    warning = FALSE)  # toggle off warning output

# load frequently used packages
library(patchwork)
library(survival)
library(survminer)
library(tidyverse)

# set default ggplot theme
courier_bw <- theme_bw() +
  theme(text = element_text(family = "Courier"),
        legend.position = "bottom")

theme_set(courier_bw)

# configure connection to mysql
source("../src/kale_mysql.R")
```

# read data

```{sql connection = kale, output.var = "censorship"}
SELECT *
FROM syn_avastin_eylea_censorship;
```

```{r}
# convert sql import to tbl
censorship <- as_tibble(censorship)
```

```{r}
# create list of filenames to read from
y <- list(
  "../data/cohort_nc.csv",
  "../data/cohort_iptw.csv",
  "../data/cohort_em.csv",
  "../data/cohort_psm.csv"
)

# read cohorts from .csv
z <- map(
  .x = y,
  ~ read_csv(
    file = .x,
    col_types = cols(
      treatment = col_factor(levels = c('eylea', 'avastin'))
    ))
)

# name each element of list
names(z) <- c('nc', 'iptw', 'em', 'psm')

# extract each elelment of list as tbl
nc <- z %>% pluck('nc')

iptw <- z %>% pluck('iptw')
  
em <- z %>% pluck('em')

psm <- z %>% pluck('psm')
```

```{r}
# Surv requires weights

nc <- mutate(nc, weights = 1)
iptw <- rename(iptw, weights = ipw)
em <- mutate(em, weights = 1)
psm <- mutate(psm, weights = 1)
```


```{r}
# source fncs
source("../fnc/survival_wrangle.R")   # joins censorship data to cohorts
source("../fnc/survival_km.R")        # models a survfit object
source("../fnc/ggsurvplot_courier.R") # plots kaplan-meiers
```

# nc

```{r}
#

nc.cens <- map2(
  .x = list(
    nc
  ),
  .y = list(
    '>=15',
    '>=10',
    '<=-15'),
  .f = ~ survival_wrangle(
    cohort_tbl = .x,
    pool_tbl = censorship,
    event = .y
  )
)

names(nc.cens) <- list(
    '>= 15',
    '>= 10',
    '<= -15')
```

```{r}
#

nc.kms <- map(
  .x = nc.cens,
  ~ survival_km(
    data = .x,
    weights = weights
  )
)
```

```{r}
# 

nc.plots <- pmap(
  list(
    nc.kms,
    nc.cens,
    names(nc.kms)),
  ~ ggsurvplot_courier(
      fit = ..1,
      data = ..2,
      title = str_c("UC ", ..3)
    )
  )
```

# iptw

```{r}
#

iptw.cens <- map2(
  .x = list(
    iptw
  ),
  .y = list(
    '>=15',
    '>=10',
    '<=-15'),
  .f = ~ survival_wrangle(
    cohort_tbl = .x,
    pool_tbl = censorship,
    event = .y
  )
)

names(iptw.cens) <- list(
    '>= 15',
    '>= 10',
    '<= -15')
```

```{r}
#

iptw.kms <- map(
  .x = iptw.cens,
  ~ survival_km(
    data = .x,
    weights = weights
  )
)
```

```{r}
#

iptw.plots <- pmap(
  list(
    iptw.kms,
    iptw.cens,
    names(iptw.kms)),
  ~ ggsurvplot_courier(
      fit = ..1,
      data = ..2,
      title = str_c("IPTW ", ..3)
    )
  )
```

# em

```{r}
#

em.cens <- map2(
  .x = list(
    em
  ),
  .y = list(
    '>=15',
    '>=10',
    '<=-15'),
  .f = ~ survival_wrangle(
    cohort_tbl = .x,
    pool_tbl = censorship,
    event = .y
  )
)

names(em.cens) <- list(
    '>= 15',
    '>= 10',
    '<= -15')
```

```{r}
#

em.kms <- map(
  .x = em.cens,
  ~ survival_km(
    data = .x,
    weights = weights
  )
)
```

```{r}
#

em.plots <- pmap(
  list(
    em.kms,
    em.cens,
    names(em.kms)),
  ~ ggsurvplot_courier(
      fit = ..1,
      data = ..2,
      title = str_c("EM ", ..3)
    )
  )
```

# psm

```{r}
#

psm.cens <- map2(
  .x = list(
    psm
  ),
  .y = list(
    '>=15',
    '>=10',
    '<=-15'),
  .f = ~ survival_wrangle(
    cohort_tbl = .x,
    pool_tbl = censorship,
    event = .y
  )
)

names(psm.cens) <- list(
    '>= 15',
    '>= 10',
    '<= -15')
```

```{r}
#

psm.kms <- map(
  .x = psm.cens,
  ~ survival_km(
    data = .x,
    weights = weights
  )
)
```

```{r}
#

psm.plots <- pmap(
  list(
    psm.kms,
    psm.cens,
    names(psm.kms)),
  ~ ggsurvplot_courier(
      fit = ..1,
      data = ..2,
      title = str_c("PSM ", ..3)
    )
  )
```

# combine plots

Using `survminer::arrange()` would be the obvious choice, but this way does not allow for a common legend:

```{r}
plots <- c(
  nc.plots,
  iptw.plots,
  em.plots,
  psm.plots
)

arrange_ggsurvplots( 
  plots, 
  print = TRUE,
  ncol = 4,
  nrow = 3)

```
Thus, a slight convoluted approach is taking using pathwork, which requires the $plot obejct to be extracted from each ggsurvplot object.

```{r}
# extract plot from each ggsurvplot

nc.a <- nc.plots[[">= 15"]][["plot"]]
nc.b <- nc.plots[[">= 10"]][["plot"]]
nc.c <- nc.plots[["<= -15"]][["plot"]]

iptw.a <- iptw.plots[[">= 15"]][["plot"]]
iptw.b <- iptw.plots[[">= 10"]][["plot"]]
iptw.c <- iptw.plots[["<= -15"]][["plot"]]

em.a <- em.plots[[">= 15"]][["plot"]]
em.b <- em.plots[[">= 10"]][["plot"]]
em.c <- em.plots[["<= -15"]][["plot"]]

psm.a <- psm.plots[[">= 15"]][["plot"]]
psm.b <- psm.plots[[">= 10"]][["plot"]]
psm.c <- psm.plots[["<= -15"]][["plot"]]
```

```{r}
(nc.a + iptw.a + em.a + psm.a + nc.b + iptw.b + em.b + psm.b + nc.c + iptw.c + em.c + psm.c)  +
  plot_layout(guides = "collect")
```

```{r}
# export as .tiff
ggsave(
  filename = "fig_4.tiff",
  plot = last_plot(),
  device = "tiff",
  path = "../figs",
  width = 178,
  height = 120,
  units = "mm",
  dpi = 300
)
```

```{r info, echo = FALSE}
print(sessionInfo())
```