---
title: "noninferiority"
author: "Darren S Thomas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
always_allow_html: yes
output: github_document
---

```{r setup, include=FALSE}
# configure Rmd chunks
knitr::opts_chunk$set(
    echo = TRUE,      # output code chunks
    message = FALSE,  # toggle off message output 
    warning = FALSE)  # toggle off warning output

# load frequently used packages
library(broom)
library(tidyverse)

# set default ggplot theme
courier_bw <- theme_bw() +
  theme(text = element_text(family = "Courier"),
        legend.position = "bottom")

theme_set(courier_bw)
```

# read_data

```{r}
# create list of filenames to read from
y <- list(
  "../data/cohort_nc.csv",
  "../data/cohort_iptw.csv",
  "../data/cohort_em.csv",
  "../data/cohort_psm.csv"
)

# read cohorts from .csv
z <- map(
  .x = y,
  ~ read_csv(
    file = .x,
    col_types = cols(
      treatment = col_factor(levels = c('eylea', 'avastin'))
    ))
)

# name each element of list
names(z) <- c('nc', 'iptw', 'em', 'psm')
```


```{r}
# impute negative ETDRS

impute_neg_etdrs <- function(x){
    # -4 is in fact etdrs 4 (1/60 snellen meters)
  x$study_exit_va[x$study_exit_va == -4] <- 4
  
  # impute counting fingers (-15 converted ETDRS) to 2
  x$study_exit_va[x$study_exit_va == -15] <- 2
  
  # impute hand motion (-30), light perception (-50), and no light perception (-165) to 0
  x$study_exit_va[x$study_exit_va < 0] <- 0
  
  x
}
```

```{r}
mean_change <- function(x){
  
  output <- x %>% 
    mutate(va_change = study_exit_va - baseline_etdrs)
  
  output
}
```

```{r}
# apply impute_neg_etdrs & mean_change to each tbl
z <- map(
  .x = z,
  ~ impute_neg_etdrs(x = .x)
  ) 

# apply mean_change to each tbl
z <- map(
  .x = z,
  ~ mean_change(x = .x)
  )
```

```{r}
# extract each elelment of list as tbl
nc <- z %>% pluck("nc")

iptw <- z %>% pluck("iptw")
  
em <- z %>% pluck("em")

psm <- z %>% pluck("psm")
```

# outcome_distributions

```{r}
# combine elements of list as tbl
z.tbl <- z %>% 
  bind_rows(.id = "cohort") %>% 
  mutate(ipw = if_else(
    cohort %in% c("em", "nc", "psm"),
    1,
    ipw
  ))
```

```{r}
# checkout outcome distirbution
z.tbl %>% 
  ggplot(aes(x = treatment, y = va_change, weight = ipw, colour = treatment)) +
  facet_wrap(~ cohort) +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75)) 
# moderate negative skew
```

```{r}
# try out reciprical + constant transformation
z.tbl %>% 
  ggplot(aes(x = treatment, y = 1 / (va_change + 100), weight = ipw, colour = treatment)) +
  facet_wrap(~ cohort) +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75))
  
```

```{r}
# summary mean exit va by treatment and cohort (iptw is NOT weighted)
z.tbl %>% 
  group_by(cohort, treatment) %>% 
  summarise(mean_exit_va = round(mean(study_exit_va), 1))
```

# nc

```{r}
# fit lm
nc.lm <- lm(
  va_change ~ 1 + treatment,
  data = nc
) %>% 
  broom::tidy(conf.int = TRUE) %>% 
  mutate(method = "NC")

nc.lm
```
# iptw

```{r}
# fit lm
iptw.lm <- lm(
  va_change ~ 1 + treatment,
  data = iptw,
  weights = ipw
) %>% 
  broom::tidy(conf.int = TRUE) %>% 
  mutate(method = "IPTW")

iptw.lm
```

# em

```{r}
# fit lm
em.lm <- lm(
  va_change ~ 1 + treatment,
  data = em
) %>% 
  broom::tidy(conf.int = TRUE) %>% 
    mutate(method = "EM")

em.lm
```

# psm

```{r}
# fit lm
psm.lm <- lm(
  va_change ~ 1 + treatment,
  data = psm
) %>% 
  broom::tidy(conf.int = TRUE) %>% 
  mutate(method = "PSM")

psm.lm
```

# forest_plot

```{r}
# extract estimates from .lm onjects
ni.lm <- bind_rows(
  nc.lm,
  iptw.lm,
  em.lm,
  psm.lm
) %>% 
  rename(
    mean_difference = estimate,
    lo95 = conf.low,
    hi95 = conf.high
  )
```

```{r}
# convert to point estimate and confidence intervals to strings (to keep trailing zeros for plot)

to_string <- function(
  var,
  n_digits = 1,
  n_small = 1){
    
  as.character(format(round(var, digits = n_digits), nsmall = n_small))
  
  }

```

```{r}
ni.lm <- ni.lm %>% 
  filter(term != "(Intercept)") %>% 
  mutate(
    mean_difference_lab = to_string(mean_difference),
    lo95_lab = to_string(lo95),
    hi95_lab = to_string(hi95),
    lab = str_c(
      str_trim(mean_difference_lab), 
      "(", 
      str_trim(lo95_lab), 
      "-", 
      str_trim(hi95_lab), 
      ")")
  ) %>% 
  mutate(method = factor(method, levels = c("PSM", "EM", "IPTW", "NC")))
```


```{r}
# forest plot
# set new default ggplot theme
courier_bw <- theme_classic() +
  theme(text = element_text(family = "Courier"),
        legend.position = "bottom",
        axis.text.y = element_text(
          face = "bold", 
          size = 14,
          hjust = 0.5),
        axis.ticks = element_blank(),
        axis.line.y = element_blank())

theme_set(courier_bw)

ni.lm %>% 
  ggplot(aes(x = mean_difference, y = method)) +
  geom_point(
    size = 6,
    shape = 18) +
  labs(
    x = "Mean difference\n(95% Confidence Interval)",
    y = NULL
  ) +
  geom_vline(
    xintercept = -4,
    linetype = "dashed",
    colour = "grey"
  ) +
  geom_errorbarh(aes(
    xmin = lo95,
    xmax = hi95,
    height = 0
  )) +
  geom_text(aes(
    family = 'Courier',
    label = lab),
    parse = FALSE,
    nudge_y = -0.2) +
  scale_x_continuous(breaks = seq(- 6, 14, 2))
```

```{r}
# export as .tiff (half-page fig)
ggsave(
  filename = "fig_2.tiff",
  plot = last_plot(),
  device = "tiff",
  path = "../figs",
  width = 86,
  height = 100,
  units = "mm",
  dpi = 300
)
```

```{r info, echo = FALSE}
print(sessionInfo())
```