---
title: "0.1_table_one"
author: "Darren S Thomas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
always_allow_html: yes
output: github_document
---

```{r setup, include=FALSE}
# configure Rmd chunks
knitr::opts_chunk$set(
    echo = TRUE,      # output code chunks
    message = FALSE,  # toggle off message output 
    warning = FALSE)  # toggle off warning output

# load frequently used packages
library(tidyverse)

# set default ggplot theme
courier_bw <- theme_bw() +
  theme(text = element_text(family = "Courier"),
        legend.position = "bottom")

theme_set(courier_bw)
```

# read_data

```{r}
# create list of filenames to read from
y <- list(
  "../data/cohort_nc.csv",
  "../data/cohort_iptw.csv",
  "../data/cohort_em.csv",
  "../data/cohort_psm.csv"
)

# read cohorts from .csv
z <- map(
  .x = y,
  ~ read_csv(
    file = .x,
    col_types = cols(
      treatment = col_factor(levels = c('eylea', 'avastin'))
    ))
)

# name each element of list
names(z) <- c('nc', 'iptw', 'em', 'psm')
```
  
```{r}
# merge to a single tbl
zz <- bind_rows(z, .id = "cohort") %>% 
  # 
  select(cohort:baseline_etdrs)
```

```{r}
# create assign_ps fnc
assign_ps <- function(
  tbl
){

  # source propensity model
  source("../src/propensity_model.R")

  # predict Pr of treatment(Avastin == 1)
  output <- augment(
   x = propensity_model,
   newdata = tbl,
   type.predict = "response") %>% 
    rename(
      ps = .fitted
    )
  
  # calculate ipw for iptw cohort, else weight = 1
  output <- output %>% 
    mutate(weight = if_else(
      cohort == "iptw", 
      case_when(treatment == "avastin" ~ 1 / ps,
                treatment == "eylea" ~ 1 / (1 - ps)),
      1))
  
  output
  }
  
```

```{r}
# score Pr
exc <- assign_ps(tbl = zz) %>% 
  # refactor sex
  mutate(gender = factor(gender, levels = c('M', 'F')))
```

# nc

```{r}
tableone::CreateTableOne(
  vars = c("gender", "age", "baseline_etdrs", "ps"),
  strata = "treatment",
  data = filter(exc, cohort == "nc"),
  test = FALSE
) %>% 
print(smd = TRUE)
```

# iptw

Calculating the weighted baseline characteristics requires an addition step using the `survey` package.

```{r}
# subset ipw so we are sure weights align with rows
iptw <- filter(exc, cohort == "iptw")
```

```{r}
iptw.svy <- survey::svydesign(
  ids = ~ 0, # no hierarchy
  weights = ~ weight,
  nest = FALSE,
  data = iptw
)
```

```{r}
tableone::svyCreateTableOne(
  vars = c("gender", "age", "baseline_etdrs", "ps"),
  strata = "treatment",
  data = iptw.svy,
  test = FALSE
) %>% 
  print(smd = TRUE)
```

# em

```{r}
tableone::CreateTableOne(
  vars = c("gender", "age", "baseline_etdrs", "ps"),
  strata = "treatment",
  data = filter(exc, cohort == "em"),
  test = FALSE
) %>% 
print(smd = TRUE)
```

# psm

```{r}
tableone::CreateTableOne(
  vars = c("gender", "age", "baseline_etdrs", "ps"),
  strata = "treatment",
  data = filter(exc, cohort == "psm"),
  test = FALSE
) %>% 
print(smd = TRUE)
```

# pre-alignment

To what extend did exchangeability hold pre-alignment?

```{r}
# configure connection to mysql
source("../src/kale_mysql.R")
```

```{sql connection = kale, output.var = 'pre'}
-- output.var = 'pre'
SELECT patient_eye AS id,
treatment,
age_at_baseline AS age,
gender,
baseline_va AS baseline_etdrs
FROM amd_synthetic_eylea_arm_study_table;
```

```{r}
pre <- pre %>% 
  # convert to tbl
  as_tibble() %>% 
  # exclude those with missing data
  drop_na(gender, age, baseline_etdrs) %>% 
  # add cohort
  mutate(cohort = "prealignment")
```

```{r}
# assign ps 
pre.ps <- assign_ps(tbl = pre) %>% 
  # add avastin trial arm
  bind_rows(filter(exc, cohort == "nc" & treatment == "avastin")) %>% 
  # refactor treatment and sex
  mutate(
    treatment = factor(treatment, levels = c('eylea', 'avastin')),
    gender = factor(gender, levels = c('M', 'F'))
  )
```

```{r}
tableone::CreateTableOne(
  vars = c("gender", "age", "baseline_etdrs", "ps"),
  strata = "treatment",
  data = pre.ps,
  test = FALSE
) %>% 
print(smd = TRUE)
```


```{r info, echo = FALSE}
print(sessionInfo())
```